import type { Ticket } from '~/shared/types/ticket';

// hardcoded transparency trailer appended to every ai-generated customer reply
export const AI_TRAILER = '\n\n---\n_Generated by AI._';

// hidden, non-configurable base instruction; the owner's system_append is concatenated after this
const BASE_SYSTEM_PROMPT = [
	'You are a customer support agent replying on behalf of a support team.',
	'Write a helpful, accurate, and concise reply to the customer.',
	"Match the tone of the conversation and address the customer's most recent message directly.",
	'Never invent policies, prices, account details, or facts you were not given; if you are unsure, say you will look into it.',
	'Reply with only the message body addressed to the customer - no subject line, no signature, no placeholders.'
].join(' ');

// a single prior turn handed to the model as conversation context
export type AiMessageTurn = { role: 'customer' | 'agent'; content: string };

export type AiReplyContext = {
	ticket: Ticket;
	// prior thread turns oldest-first (optional; the caller decides how much to include)
	history?: AiMessageTurn[];
	// resolved placeholder text injected as extra system context
	extraContext?: string;
};

export type AiReplyResult = {
	text: string;
	model: string;
};

// true when the owner enabled ai replies and a cloudflare account + token are linked
export async function isAiEnabled(env: any): Promise<boolean> {
	const ai = await getAiSettings();
	if (!ai.enabled) return false;
	const cf = await getCloudflareSettings();
	// sealed/linked token first, then env (a ui-linked account stores it sealed, not in env)
	return Boolean(cf.account_id && (await resolveCloudflareToken(env)));
}

// whether the linked cloudflare account can actually drive workers ai (account + token + scope)
export async function aiCapability(env: any): Promise<{ capable: boolean; reason?: string }> {
	setMockCf(isMockCf(env));
	if (isMockCf(env)) return { capable: true };
	try {
		const cf = await getCloudflareSettings();
		const sealed = await kv.get<any>('smoke:setting:cloudflare_token', 'json').catch(() => null);
		const token = sealed ? await openSecret(sealed, env.MASTER_KEY).catch(() => '') : '';
		if (!token || !cf.account_id)
			return { capable: false, reason: 'Link a Cloudflare account first' };
		const scopes = await getTokenScopes(token);
		const ai = cloudflareCapabilities(scopes).find((c) => c.key === 'ai');
		if (!ai?.granted) {
			return {
				capable: false,
				reason: 'Your Cloudflare API token is missing the Workers AI permission'
			};
		}
		return { capable: true };
	} catch {
		return { capable: false, reason: 'Could not verify Workers AI access' };
	}
}

type ChatMessage = { role: 'system' | 'user' | 'assistant'; content: string };

// assemble the system prompt from the fixed base + owner additions + resolved extra context
function buildSystemPrompt(ticket: Ticket, systemAppend?: string, extraContext?: string): string {
	const parts = [BASE_SYSTEM_PROMPT];
	if (systemAppend && systemAppend.trim()) parts.push(systemAppend.trim());
	if (ticket.title && ticket.title.trim())
		parts.push(`The ticket subject is: "${ticket.title.trim()}".`);
	if (extraContext && extraContext.trim())
		parts.push(`Additional context:\n${extraContext.trim()}`);
	return parts.join('\n\n');
}

// map the ticket + thread into an openai-style chat message list
function buildChatMessages(context: AiReplyContext, systemAppend?: string): ChatMessage[] {
	const messages: ChatMessage[] = [
		{
			role: 'system',
			content: buildSystemPrompt(context.ticket, systemAppend, context.extraContext)
		}
	];

	// the ticket description is the customer's opening message; the thread holds the follow-ups
	const opening = context.ticket.description?.trim();
	if (opening) messages.push({ role: 'user', content: opening });

	for (const turn of context.history ?? []) {
		const content = turn.content?.trim();
		if (!content) continue;
		messages.push({ role: turn.role === 'agent' ? 'assistant' : 'user', content });
	}

	return messages;
}

// deterministic offline reply so the mock-cf e2e lane never touches the network
function mockReply(context: AiReplyContext, model: string): AiReplyResult {
	const subject = context.ticket.title?.trim() || 'your request';
	return {
		text: `Thanks for reaching out about "${subject}". We are looking into it and will follow up shortly.`,
		model
	};
}

// generate a support reply from the configured cloudflare ai model; returns null when disabled or on
// failure so callers can fall back gracefully. never throws
export async function generateAiReply(
	context: AiReplyContext,
	env: any
): Promise<AiReplyResult | null> {
	if (!(await isAiEnabled(env))) return null;

	const ai = await getAiSettings();
	const model = ai.model || DEFAULT_AI_MODEL;

	if (isMockCf(env)) return mockReply(context, model);

	try {
		const cf = await getCloudflareSettings();
		// sealed/linked token first, then env (a ui-linked account stores it sealed, not in env)
		const token = await resolveCloudflareToken(env);
		if (!cf.account_id || !token) return null;

		const body: Record<string, unknown> = {
			messages: buildChatMessages(context, ai.system_append)
		};
		if (typeof ai.temperature === 'number') body.temperature = ai.temperature;
		if (typeof ai.max_tokens === 'number') body.max_tokens = ai.max_tokens;

		const url = `https://api.cloudflare.com/client/v4/accounts/${cf.account_id}/ai/run/${model}`;
		const res = await fetch(url, {
			method: 'POST',
			headers: {
				Authorization: `Bearer ${token}`,
				'Content-Type': 'application/json'
			},
			body: JSON.stringify(body)
		});

		const json: any = await res.json().catch(() => null);
		if (!res.ok || json?.success === false) return null;

		// text-generation models return result.response
		const text = typeof json?.result?.response === 'string' ? json.result.response.trim() : '';
		if (!text) return null;

		return { text, model };
	} catch {
		return null;
	}
}
